### ISSUE TITLE
About some performance comparison

### ISSUE THREAD

**Issue by concon23** [HICAI-ZJU/KANO#1]
Hi, thank you very much for sharing your great work. 
It is greatly interesting!

I have a bit question about Table 1 and 2.
It seems that MolCLR for MUV (in Table 1) and GLOVER for physical chemistry (in Table 2) would possibly be better when I read the original papers. 
I might misunderstand, but is there some difference in experimental conditions from the original ones?
I want to understand a little more precisely how each method performs in the same conditions.

Thank you in advance.

**Comment by ZJU-Fangyin** [comment]
Thank you for your interest in our paper. We would like to provide further clarification regarding the results presented in Tables 1 and 2.

All the results reported in the two tables were obtained by independently running the official code provided by each paper three times and then averaging the results. Specifically, we used the MolCLR code from https://github.com/yuyangw/MolCLR and the GROVER code from https://github.com/tencent-ailab/grover to ensure that we followed the same setting as the original papers. 

However, it appears that the reproduced results are indeed lower than those reported in the original papers.

Thank you again for your interest in our work, and please let me know if you have any further questions or concerns.

**Comment by concon23** [comment]
@ZJU-Fangyin 
Thank you for your kind reply. I now understand the experimental condition.
I can see full of possibility for the future in your research.
Have a nice day!

**Comment by ZJU-Fangyin** [comment]
Thank you for your positive feedback and interest in our research. Have a great day too! ☺️
