### ISSUE TITLE
OWL File Understanding

### ISSUE THREAD

**Issue by Pixelatory** [HICAI-ZJU/KANO#15]
I'm having a little trouble understanding some properties in the .owl file.

With the first entry "http://www.semanticweb.org/ElementKG#Sc", what does hasBoilingPoint7 mean with reference to the other elements? Also, what does hasHardness3 mean?

I am just not understanding why there's a 7 at the end of the hasBoilingPoint, and what this property has to do in relation with the other elements listed under "http://www.semanticweb.org/ElementKG#Sc".

**Comment by ZJU-Fangyin** [comment]
The numbers that you see at the end of property names like hasBoilingPoint7 and hasHardness3 are indicative of groups or categories that these elements fall into, based on the discretization of continuous chemical attribute values. This is a method we utilized to facilitate the interconnection of different element entities within our knowledge graph.

In the specific section "ElementKG construction and representation" (fourth paragraph) of our [paper](https://www.nature.com/articles/s42256-023-00654-0#Sec14), we have detailed this process. To provide a brief overview, we discretize the continuous chemical attribute values of elements and utilize them as object properties (like inRadiusGroup1 and inWeightGroup2) to establish connections between different element entities. In this case, the “7” in hasBoilingPoint7 and the “3” in hasHardness3 denote specific groups that these elements are categorized into based on their boiling point and hardness values, respectively.

I hope this helps in understanding the properties of the .owl file.

**Comment by Pixelatory** [comment]
Yes that helped a lot, thank you. Just one more thing: do you have the scripts for the discretization of the attributes? I could not find that in this repository.

**Comment by ZJU-Fangyin** [comment]
Since the OWL file was primarily constructed manually, we do not have specific scripts for the discretization of attributes.

**Comment by Pixelatory** [comment]
That's okay. Thank you for the help, and very nice work.

**Comment by ZJU-Fangyin** [comment]
Thank you very much for your attention!
