### ISSUE TITLE
functional_group 疑惑

### ISSUE THREAD

**Issue by Sakura4036** [HICAI-ZJU/KANO#16]
为什么使用的`fg_states`长度固定为13？是通过预训练数据集中分子匹配的funcgroup长度分布来决定的吗？

并且`fg_emb`有一个全1的起始embedding， 类似于cls token？

![image](https://github.com/HICAI-ZJU/KANO/assets/42060616/60028394-e290-4f1d-bfa2-8f8471ecbabc)

同时我还想了解一下除了`functional_prompt`的模型测试结果，你们给出的`finetune_add` 和`finetune_concat`这两个引入 functional group knowledge的模型表现怎么样？

望百忙中解我之惑，感谢！

**Comment by ZJU-Fangyin** [comment]
您好，感谢您的关注！

1. `fg_states`长度固定为13的意思是只考虑每个分子中识别到的前13个functional groups（根据统计，大多数分子包含的官能团个数都不超过这个值）。
2. 给`fg_emb`起始部分添加全为1的向量是为了方便后续与atom_hiddens进行交互，因为最终得到的atom_hiddens的起始部分也是全为1的向量。
3. `finetune_add`和`finetune_concat`的模型表现可参见[图2](https://www.nature.com/articles/s42256-023-00654-0/figures/6).

希望能解决您的疑惑！

**Comment by Sakura4036** [comment]
好的， 感谢解惑
