### ISSUE TITLE
关于如何找文章中官能团知识图谱的数据

### ISSUE THREAD

**Issue by Cy-cc** [HICAI-ZJU/KANO#17]
冒昧提问，想咨询下关于文章中官能团部分知识图谱的数据在源代码中哪一部分，也是在**`elementkg.owl`**这一部分嘛？方便指导下如何找这一块的数据嘛。谢谢~

**Comment by ZJU-Fangyin** [comment]
您好，官能团部分数据也包含在`elementkg.owl`中。您可以下载软件Protege读取知识图谱:
![image](https://github.com/HICAI-ZJU/KANO/assets/61076726/fd25969d-f53f-474b-8b6a-249752693371)
这样可以更方便理解和获取这部分数据：
<img width="1185" alt="image" src="https://github.com/HICAI-ZJU/KANO/assets/61076726/d540d99d-c5ea-4f93-89a9-a83214d3a85f">

**Comment by Cy-cc** [comment]
第一次这么及时的**issue**反馈，十分感谢~
