### ISSUE TITLE
关于如何绘制图3b

### ISSUE THREAD

**Issue by wuyuhui-zju** [HICAI-ZJU/KANO#18]
你好，我对图3b的表示方法很感兴趣。我注意到文中提到"we first map them onto the unit hypersphere S1 using t-SNE, and then visualize the density distributions of the representations..."，请问如何用t-SNE将表征映射到单位圆上？如果可以的话，能否提供一下相应的code？谢谢

**Comment by ZJU-Fangyin** [comment]
<img width="686" alt="image" src="https://github.com/HICAI-ZJU/KANO/assets/61076726/13e93593-a7ea-465d-96ab-2bcd80f4ab58">

你好，你可以参考上述代码，先用t-SNE映射到2维表示再做归一化。

**Comment by wuyuhui-zju** [comment]
感谢分享！

**Comment by coderabbittank** [comment]
I am also interested in the circle plotting and density plot of figure 3b, can you provide the full code for me to learn?

**Comment by coderabbittank** [comment]
I am also interested in the circle plotting and density plot of figure 3b, can you provide the full code for me to learn?
