### ISSUE TITLE
关于将模型应用在下游预测任务的问题

### ISSUE THREAD

**Issue by ABlueCat123** [HICAI-ZJU/KANO#19]
老师您好！十分感谢您的工作，我们受益匪浅。
不过我有一个问题想请教您，那就是如何利用已经微调好的模型用于无标签数据集的预测上面？恕我愚钝，我可能没有发现相关代码，望指教！

**Comment by ZJU-Fangyin** [comment]
您好，根据您的需求我添加了predict.py文件，并更新了README，您可以根据需要在自己的数据上做预测。记得替换模型地址和预测数据地址。祝顺利。
<img width="676" alt="image" src="https://github.com/HICAI-ZJU/KANO/assets/61076726/9b1051a5-6b7c-4994-9467-892929a8ca62">

**Comment by ABlueCat123** [comment]
真的十分感谢，我尝试一下，祝顺利！

**Comment by ABlueCat123** [comment]
> 您好，根据您的需求我添加了predict.py文件，并更新了README，您可以根据需要在自己的数据上做预测。记得替换模型地址和预测数据地址。祝顺利。 <img alt="image" width="676" src="https://private-user-images.githubusercontent.com/61076726/300264696-9b1051a5-6b7c-4994-9467-892929a8ca62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NDc5ODgsIm5iZiI6MTcwNjQ0NzY4OCwicGF0aCI6Ii82MTA3NjcyNi8zMDAyNjQ2OTYtOWIxMDUxYTUtNmI3Yy00OTk0LTk0NjctODkyOTI5YThjYTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDEzMTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmNmFjMDI0MGMyNTQ2MzdmMDZmZjk0YWIzMzI4YjExOTgzNDQwNDY2MDg0OTI5OTMxZmQ0YWQ4ZTMyZWRkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WZmAerfdt5N050S7EiKW7ImEb30C2Gmk7ZJQCmMUOGg">

真的十分感谢，我尝试一下，祝顺利！

**Comment by ZJU-Fangyin** [comment]
记得更新一下整个项目，为了让predict.py顺利运行，我修改了其他部分的一些代码。

**Comment by ABlueCat123** [comment]
> 记得更新一下整个项目，为了让predict.py顺利运行，我修改了其他部分的一些代码。

明白了，十分感谢您的提醒。

**Comment by ABlueCat123** [comment]
> 记得更新一下整个项目，为了让predict.py顺利运行，我修改了其他部分的一些代码。

老师您好，抱歉再次就这个问题打扰您。predict.py文件里面有用到./dumped/pretrained_graph_encoder/original_CMPN_0623_1350_14000th_epoch.pt文件，但项目中貌似没有这个文件。且将同名的pkl文件改为pt貌似也没用。请问应该如何解决？
报错为：
![QQ图片20240131214449](https://github.com/HICAI-ZJU/KANO/assets/35156118/11c08e64-d098-49e1-8b8b-97e5236ee950)
```
Traceback (most recent call last):
  File "/root/Desktop/KANO-main/predict.py", line 23, in <module>
    pred, smiles = make_predictions(args, data.smiles.tolist())
  File "/root/Desktop/KANO-main/chemprop/train/make_predictions.py", line 29, in make_predictions
    scaler, features_scaler = load_scalers(args.checkpoint_paths[0])
  File "/root/Desktop/KANO-main/chemprop/utils.py", line 129, in load_scalers
    state['data_scaler']['stds']) if state['data_scaler'] is not None else None
KeyError: 'data_scaler'
```

**Comment by ZJU-Fangyin** [comment]
这个`./dumped/pretrained_graph_encoder/original_CMPN_0623_1350_14000th_epoch.pt`文件需要替换成你自己微调好的模型。
根据您的问题：“如何利用已经微调好的模型用于无标签数据集的预测上面”，您应该已经有微调好的模型了，替换成你微调好的模型就可以了。predict.py文件里的模型只是一个实例。
