### ISSUE TITLE
关于官能团表是否有个小错误

### ISSUE THREAD

**Issue by ABlueCat123** [HICAI-ZJU/KANO#21]
作者您好，请问在伯胺、仲胺、叔胺的官能团表中：
PrimaryAmine            [NX3;H2,H1;!$(NC=O)]
SecondaryAmine          [NX3;**H2**;!$(NC=O)]
TertiaryAmine           [NX3;!$(NC=O)]
仲胺这里是不是应该是H1？因为貌似这里的含义是仲胺必须连接2个氢原子，这似乎是伯胺的定义。然后伯胺处为何2个氢原子和1个氢原子都可以被视为伯胺呢？
例如我的输入为CNC的时候，输出了PrimaryAmine和TertiaryAmine，或许可能有误，谢谢！

**Comment by ZJU-Fangyin** [comment]
非常感谢您的提醒！我参考的资料来源于[Daylight](https://www.daylight.com/dayhtml_tutorials/languages/smarts/smarts_examples.html)，其中并未对Primary Amine和Secondary Amine进行明确区分。因此在手动修改过程中可能导致了错误。现在我已根据您的建议对数据进行了相应的调整。再次感谢您的帮助！

**Comment by ABlueCat123** [comment]
> 非常感谢您的提醒！我参考的资料来源于[Daylight](https://www.daylight.com/dayhtml_tutorials/languages/smarts/smarts_examples.html)，其中并未对Primary Amine和Secondary Amine进行明确区分。因此在手动修改过程中可能导致了错误。现在我已根据您的建议对数据进行了相应的调整。再次感谢您的帮助！

感谢回复！目前问题应该解决了。
