### ISSUE TITLE
Where does augmentation happen in pretraining?

### ISSUE THREAD

**Issue by soulios** [HICAI-ZJU/KANO#24]
Hello!

Very cool idea and repo but I cannot see where exactly in the code the augmentation happens to constrast the moelcules in the pretraining.
Can you maybe point it out?
Thanks in advance.

**Comment by Fangyinfff** [comment]
Hi,

You can find the code for augmentation at [here](https://github.com/HICAI-ZJU/KANO/blob/main/chemprop/features/featurization.py#L248-L317), and the code for contrastive learning at [here](https://github.com/HICAI-ZJU/KANO/blob/main/chemprop/train/run_training.py#L415-L418).

I hope this helps!
