### ISSUE TITLE
Question Regarding the Baseline Performance of CMPNN in Your Paper

### ISSUE THREAD

**Issue by mxqmxqmxq** [HICAI-ZJU/KANO#26]
May I kindly ask if you would be able to share the random seeds used in your replication of the CMPNN model? I have been following the procedure you mentioned—"We perform three independent runs on three random-seeded scaffold splitting for all datasets"—but in my replication, the results tend to hover around a 3 repeats score of 0.94436 ± 0.01183, whereas the results in your paper show 92.7 ± 1.7. I am wondering if you might be able to share the baseline random seeds you used for your experiments.

Additionally, I wanted to express my admiration for your prior work, such as KANO and KCL. Thank you very much for your time and assistance.

**Comment by Fangyinfff** [comment]
Hi, 

Thank you very much for your attention. I’ve tried searching the server for the exact random seeds used but unfortunately couldn’t locate the records. In my experiments, I generally run the results 10 times and then select 3 runs to calculate the mean and standard deviation. Maybe you can try using seeds in the range of 0-9 or 43-53.

I hope this helps.

**Comment by mxqmxqmxq** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣  Thank you very much for your prompt and detailed response! I will try it later！

**Comment by mxqmxqmxq** [comment]
<img width="852" alt="image" src="https://github.com/user-attachments/assets/42f13783-b0a0-4a90-a40c-84ec7d91c0b3">
I came across something quite interesting that I wanted to get your thoughts on. In "From molecules to scaffolds to functional groups: building context-dependent molecular representation via multi-channel learning," on page 15, I noticed that KANO’s performance on the BBBP dataset is reported as 69.9 ± 1.9. I’m curious to know how you view this result and if there might be specific factors contributing to this level of performance.

**Comment by Fangyinfff** [comment]
Hi, thank you very much for pointing that out! I read the original text and noticed how they described their data splitting method. 

<img width="853" alt="image" src="https://github.com/user-attachments/assets/9ca68beb-bcbb-4d04-871f-32736637a0d8">

I think the difference in results might be due to using different data splits.

**Comment by mxqmxqmxq** [comment]
Okk! I see! Thank you very much for your detailed response!
