### ISSUE TITLE
Request for Specific Implementation in KANO

### ISSUE THREAD

**Issue by Andy6M** [HICAI-ZJU/KANO#4]
Hello,

I am working with the KANO library and I am interested in the "Fig.4 Investigation of interpretability of functional prompts" section mentioned in the original paper.

Can you guide me to where in the KANO library this is implemented? I'm also looking for any related visualization code.

If it's not currently included, could it be added?

Thank you.

**Comment by ZJU-Fangyin** [comment]
Hello,

Thank you for your interest in our work.

Regarding the "Fig.4 Investigation of interpretability of functional prompts" mentioned in the original paper, there isn't direct code available that outputs the figure as is. The generation of this figure is a process that requires calculating the attention values for each functional group and using a visualization tool (such as PowerPoint, Adobe Illustrator, or ChemDraw) to annotate these values onto the molecular graph.

The KANO library doesn't directly provide these steps or include visualization tools for this specific purpose. These steps formed a part of a process that was specifically tailored for our research needs and may not directly translate to broader usage scenarios. You may consider implementing these steps yourself using the existing functionalities provided by KANO and any other tool you prefer for the visualization.

Thank you again for your interest and feedback!
