### ISSUE TITLE
Problem of finetuning and predicting in custom dataset

### ISSUE THREAD

**Issue by medicine-wave** [HICAI-ZJU/KANO#5]
If I have a custom dataset .csv file, how can I use KANO for finetuning(this can refer finetune.sh) and predicting(not mentioned) ?

**Comment by ZJU-Fangyin** [comment]
Sure, your question can be addressed by referring to the way mentioned in this link: https://github.com/HICAI-ZJU/KANO#conducting-experiments-on-a-specified-dataset. 

Here is a specific example of how to use a custom .csv file for fine-tuning or prediction:
```
python train.py \
    --data_path $../your_train.csv$ \
    --separate_test_path $../your_test.csv$ \
    --separate_val_path $../your_val.csv$ \
    --dataset_type $classification$ \
    --epochs 100 \
    --num_runs 1 \
    --gpu 1 \
    --batch_size 256 \
    --step 'functional_prompt' \
    --exp_name finetune \
    --exp_id your_exp_id \
    --checkpoint_path "./dumped/pretrained_graph_encoder/original_CMPN_0623_1350_14000th_epoch.pkl"
```
In this script, `--data_path`, `--separate_test_path`, and `--separate_val_path` are the paths to your custom .csv files for training, testing, and validation, respectively.

**Comment by medicine-wave** [comment]
Thanks for your rapid reply, I will try!
