### ISSUE TITLE
如何提取预训练特征来给其他下游模型进行训练？

### ISSUE THREAD

**Issue by iPFAS** [HICAI-ZJU/KANO#7]
您好 
    我想将预训练的特征抓出来进行下游模型训练或者做相关的分析
    我调整了KANO-main/chemprop/models/cmpn.py的代码如下
![image](https://github.com/HICAI-ZJU/KANO/assets/114653967/ca248cb2-e7b8-4383-a53e-1d932a9df146)
通过截取特征输出，输出的特征文件包括600个特征，可是经过去除低方差和高相关性处理后剩余65个，利用xbg算法训练得到的结果值偏离正常值，属于无效数据，但是直接预训练得到的指标比较正常，想咨询下可能的问题在哪？下面附上我的全部改动
使用的是自定义数据集
KANO-main/chemprop/train/run_training.py
![image](https://github.com/HICAI-ZJU/KANO/assets/114653967/75840a22-3dc8-456d-a828-a2eca8513bb3)
KANO-main/chemprop/train/predict.py
![image](https://github.com/HICAI-ZJU/KANO/assets/114653967/698519be-b37f-4f31-9174-e3a74adc0515)
KANO-main/chemprop/models/model.py
![image](https://github.com/HICAI-ZJU/KANO/assets/114653967/b83c2152-c63c-47e1-b44c-4810b3629b5f)

考虑得你们文中也做过t-SNE分析，应该是有获取特征的思路的，所以希望能得到您的帮助，万分感谢！

**Comment by ZJU-Fangyin** [comment]
您好，您可以参考或直接使用[get_embs](https://github.com/HICAI-ZJU/KANO/blob/main/chemprop/train/make_predictions.py#L96)函数来获取预训练特征。希望能够帮到您！

**Comment by iPFAS** [comment]
好的 我明白了 谢谢您的帮助
