### ISSUE TITLE
How to get the prediction output seperately?

### ISSUE THREAD

**Issue by WeiJunZhou23** [HICAI-ZJU/KANO#8]
Hi,
I want to know is there a function that I can output the prediction for each smiles, 
for example:
`smiles,class`
`O1CC[C@@H](NC(=O)[C@@H](Cc2cc3cc(ccc3nc2N)-c2ccccc2C)C)CC1(C)C,1`
I want the prediction of this smiles (0 or 1)

Thank you.

**Comment by ZJU-Fangyin** [comment]
Hello,

Thank you for your interest in our work. If you want to get the prediction for a specific SMILES, you can use the [predict](https://github.com/HICAI-ZJU/KANO/blob/main/chemprop/train/predict.py#L11) function. 
```python

with torch.no_grad():
    batch_preds = model(step, prompt, batch, features_batch)
batch_preds = batch_preds.data.cpu().numpy()
```
Here, ``batch`` refers to the batch of molecules you input, and ``batch_preds`` represents the prediction for each molecule in the batch. You can modify and print the input and output of this function according to your needs.

I hope this helps!
