### ISSUE TITLE
augmentation in pre-training

### ISSUE THREAD

**Issue by ZixuanFeng-NYU** [HICAI-ZJU/KANO#9]
in def pre_training(args: Namespace, logger: Logger = None) -> List[float]:
...
  emb1 = model1(step, False, batch, None)
  emb2 = model2(step, True, batch, None)
  
  
  Is False/True here meaning data augmentation or not?

**Comment by ZJU-Fangyin** [comment]
Yes, you are correct. In this context, `False` indicates that graph augmentation is not being performed, while `True` signifies that graph augmentation is being carried out.
